=== varoxid/xml-basics/3_xsd/lessons/lessons_XML.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="lessons">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="lesson" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="teacher" type="xs:string"/>
                            <xs:element name="datePeriod" type="xs:string"/>
                            <xs:element name="hours" type="xs:positiveInteger"/>
                            <xs:element name="type">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="зачёт"/>
                                        <xs:enumeration value="экзамен"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:integer" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== varoxid/xml-basics/4_xpath/lessons_v1/lessons.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="less_template_2.xsl"?>
<lessons xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="lessons_XML.xsd">
    <lesson id="1">
        <name>Технологии программирования</name>
        <teacher>доцент Осипов Н.А.</teacher>
        <datePeriod>25 апреля - 16 апреля 2024 г.</datePeriod>
        <hours>50</hours>
        <type>зачёт</type>
    </lesson>
    <lesson id="2">
        <name>Введение в базы данных</name>
        <teacher>ст. преп. Осетрова И.С.</teacher>
        <datePeriod>18 апреля - 7 мая 2024 г.</datePeriod>
        <hours>35</hours>
        <type>зачёт</type>
    </lesson>
    <lesson id="3">
        <name>Программирование C#</name>
        <teacher>доцент Осипов Н.А.</teacher>
        <datePeriod>13 мая - 31 мая 2024 г.</datePeriod>
        <hours>50</hours>
        <type>зачёт</type>
    </lesson>
    <lesson id="4">
        <name>PL/pgSQL и реализация баз данных PostgreSQL</name>
        <teacher>ст. преп. Ямщиков Д.В.</teacher>
        <datePeriod>3 июня - 28 июня 2024 г.</datePeriod>
        <hours>60</hours>
        <type>экзамен</type>
    </lesson>
    <lesson id="5">
        <name>Разработка Windows-приложений</name>
        <teacher>доцент Осипов Н.А.</teacher>
        <datePeriod>1 июля - 19 июля 2024 г.</datePeriod>
        <hours>50</hours>
        <type>зачёт</type>
    </lesson>
    <lesson id="6">
        <name>Основы технологий разметки (HTML, XML)</name>
        <teacher>ст. преп. Марченко Е.В.</teacher>
        <datePeriod>22 июля - 31 июля 2024 г.</datePeriod>
        <hours>25</hours>
        <type>зачёт</type>
    </lesson>
    <lesson id = "7">
        <name>Технология ADO.NET</name>
        <teacher>ст. преп. Кузьмин К.М.</teacher>
        <datePeriod>9 – 27 сентября</datePeriod>
        <hours>40</hours>
        <type>зачёт</type>
    </lesson>
    <lesson id = "8">
        <name>Разработка Web-приложений с использованием технологии ASP.NET</name>
        <teacher>доцент Осипов Н.А.</teacher>
        <datePeriod>30 сентября – 21 октября</datePeriod>
        <hours>50</hours>
        <type>экзамен</type>
    </lesson>
</lessons>
