=== varoxid/xml-basics/4_xpath/resume_v1/resume.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:simpleType name="phoneType">
        <xs:restriction base="xs:string">
            <xs:pattern value="\+\d{1,3}\s\(\d{3}\)\s\d{3}-\d{2}-\d{2}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="dateType">
        <xs:restriction base="xs:date">
            <xs:minInclusive value="1947-01-01"/>
            <xs:maxInclusive value="1992-01-01"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="maritalStatusType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="женат"/>
            <xs:enumeration value="не женат"/>
            <xs:enumeration value="замужем"/>
            <xs:enumeration value="не замужем"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="educationType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="высшее"/>
            <xs:enumeration value="среднее"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="AgeType">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="20"/>
            <xs:maxInclusive value="65"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="resumes">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="candidate" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="firstName" type="xs:string"/>
                            <xs:element name="lastName" type="xs:string"/>
                            <xs:element name="middleName" type="xs:string" minOccurs="0"/>
                            <xs:element name="currentWorkplace" type="xs:string"/>
                            <xs:element name="currentPosition" type="xs:string"/>
                            <xs:element name="birthDate" type="dateType"/>
                            <xs:element name="age" type="AgeType"/>
                            <xs:element name="education" type="educationType"/>
                            <xs:element name="address" type="xs:string"/>
                            <xs:element name="phone" type="phoneType"/>
                            <xs:element name="maritalStatus" type="maritalStatusType"/>
                            <xs:element name="desiredSalary" type="xs:positiveInteger"/>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:integer" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== varoxid/xml-basics/4_xpath/resume_v1/resume.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="resume_template.xsl"?>
<resumes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="resume.xsd">
    <candidate id="1">
        <firstName>Иван</firstName>
        <lastName>Иванов</lastName>
        <middleName>Иванович</middleName>
        <currentWorkplace>ООО "Компания"</currentWorkplace>
        <currentPosition>Старший разработчик</currentPosition>
        <birthDate>1990-01-01</birthDate>
        <age>35</age>
        <education>высшее</education>
        <address>г. Москва, ул. Ленина, д. 1, кв. 2</address>
        <phone>+7 (999) 999-99-99</phone>
        <maritalStatus>женат</maritalStatus>
        <desiredSalary>190000</desiredSalary>
    </candidate>
    <candidate id="2">
        <firstName>Мария</firstName>
        <lastName>Иванова</lastName>
        <middleName>Сергеевна</middleName>
        <currentWorkplace>АО "Финансовые решения"</currentWorkplace>
        <currentPosition>Менеджер</currentPosition>
        <birthDate>1991-12-31</birthDate>
        <age>30</age>
        <education>высшее</education>
        <address>г. Санкт-Петербург, ул. Пушкина, д. 1, кв. 2</address>
        <phone>+7 (944) 444-44-44</phone>
        <maritalStatus>не замужем</maritalStatus>
        <desiredSalary>100000</desiredSalary>
    </candidate>
</resumes>
